language: cpp
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq gperf autotools-dev librecon-dev
compiler:
 - gcc
 - clang
script:
 - ./build/travis/bootstrap
 - ./build/travis/configure
 - ./build/travis/build

