language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gperf autotools-dev
 - sudo add-apt-repository -y "deb http://http.us.debian.org/debian/ jessie main"
 - sudo add-apt-repository -y "deb http://http.us.debian.org/debian/ jessie-backports main"
 - sudo apt-get update -qq
 - sudo apt-get install -qq -t jessie-backports librecon-dev
compiler:
 - gcc
 - clang
script:
 - ./build/travis/bootstrap
 - ./build/travis/configure
 - ./build/travis/build

